`timescale 1ns / 1ps

module tb_mwc_pre_processing_top;

    // --- System Register & Parameter Settings ---
    parameter DATA_WIDTH        = 16;
    parameter COEFF_WIDTH       = 16;
    parameter HS_NUM_TAPS       = 16;  // Matches your MATLAB setup
    parameter HC_NUM_TAPS       = 16;  // Matches your MATLAB setup
    parameter DATA_FRAC_WIDTH   = 8;
    parameter COEFF_FRAC_WIDTH  = 8;
    parameter U_FACTOR          = 4;
    parameter D_FACTOR          = 4;
    
    parameter CLK_PERIOD        = 10;  // 100 MHz fast master clock
    parameter TOTAL_SAMPLES     = 512; // Matching the MATLAB FFT grid size

    // --- Wires and Registers to Drive the Design ---
    reg                         clk;
    reg                         rst_n;
    reg  signed [DATA_WIDTH-1:0] adc_din;
    reg                         adc_din_valid;
    
    // Paste the Hex parameters generated by your MATLAB script directly here
    reg [HS_NUM_TAPS*COEFF_WIDTH-1:0] hs_coeff_vector;
    reg [HC_NUM_TAPS*COEFF_WIDTH-1:0] hc_coeff_vector;
    
    wire signed [DATA_WIDTH-1:0] clean_dout;
    wire                         clean_dout_valid;

    // --- File Handlers for I/O Log Streams ---
    integer out_file;
    integer sample_idx;

    // --- Simulated Hardware Memory Array ---
    // This holds the distorted signal array extracted from MATLAB
    reg [DATA_WIDTH-1:0] adc_raw_mem [0:TOTAL_SAMPLES-1];

    // =========================================================================
    // Device Under Test (DUT) Instantiation
    // =========================================================================
    mwc_pre_processing_top #(
        .DATA_WIDTH(DATA_WIDTH),
        .COEFF_WIDTH(COEFF_WIDTH),
        .HS_NUM_TAPS(HS_NUM_TAPS),
        .HC_NUM_TAPS(HC_NUM_TAPS),
        .DATA_FRAC_WIDTH(DATA_FRAC_WIDTH),
        .COEFF_FRAC_WIDTH(COEFF_FRAC_WIDTH),
        .U_FACTOR(U_FACTOR),
        .D_FACTOR(D_FACTOR)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .adc_din(adc_din),
        .adc_din_valid(adc_din_valid),
        .hs_coeff_vector(hs_coeff_vector),
        .hc_coeff_vector(hc_coeff_vector),
        .clean_dout(clean_dout),
        .clean_dout_valid(clean_dout_valid)
    );

    // =========================================================================
    // Clock Generation Network
    // =========================================================================
    always begin
        clk = 1'b0;
        #(CLK_PERIOD / 2);
        clk = 1'b1;
        #(CLK_PERIOD / 2);
    end
    
    integer out_fid;

initial begin
    out_fid = $fopen("hardware_dout.txt", "w");
    if (out_fid == 0) begin
        $display("Error creating output file!");
        $finish;
    end
end

always @(posedge clk) begin
    if (clean_dout_valid) begin
        // Write out the hex value line by line
        $fwrite(out_fid, "%h\n", clean_dout);
    end
end

// Close the file when simulation finishes (e.g., when sample_idx hits a limit)
always @(posedge clk) begin
    if (sample_idx == 511) begin // Adjust to your total number of samples
        $fclose(out_fid);
        $display("Output file saved successfully.");
    end
end

    // =========================================================================
    // Main Simulation Execution Loop
    // =========================================================================
    initial begin
        // Initialize Core Ports
        rst_n         = 1'b0;
        adc_din       = {DATA_WIDTH{1'b0}};
        adc_din_valid = 1'b0;
        
        // Load the static filter arrays calculated by your script
        // Note: Replace these placeholder values with your actual MATLAB console output strings
        hs_coeff_vector = 256'hFFF2FFEBFFF000000013001D00170000FFE2FFCFFFD700000045009300CF00E6;
        hc_coeff_vector = 256'hFFFBFFEDFFEAFFF300060019001E0011FFF4FFD6FFC9FFDD0014006300B200E6;

        // Load the input waveform data generated from MATLAB
        $readmemh("adc_din.txt", adc_raw_mem);

        // Open an empty text output file to log clean hardware tracking traces
        out_file = $fopen("clean_dout.txt", "w");
        if (out_file == 0) begin
            $display("[TB ERROR] Failed to create or write clean_dout.txt file output. Aborting simulation.");
            $finish;
        end

        // De-assert system reset after 5 clock cycles
        #(CLK_PERIOD * 5);
        @(posedge clk);
        rst_n = 1'b1;
        #(CLK_PERIOD * 2);
        
        $display("[TB START] Reset dropped. Streaming %d samples from adc_din.txt into MWC...", TOTAL_SAMPLES);

        // Stream time-domain samples through the architecture
        // The ADC feeds data on a slow cadence (e.g., matching downsampling factors)
        for (sample_idx = 0; sample_idx < TOTAL_SAMPLES; sample_idx = sample_idx + 1) begin
            @(posedge clk);
            adc_din       = adc_raw_mem[sample_idx];
            adc_din_valid = 1'b1;
            
            // Wait for U_FACTOR-1 cycles to mimic slower ADC clock cadence 
            // relative to the high-frequency internal processing pipeline
            repeat (U_FACTOR - 1) begin
                @(posedge clk);
                adc_din_valid = 1'b0; 
            end
        end

        // Stop streaming and clear interface lines
        @(posedge clk);
        adc_din_valid = 1'b0;
        adc_din       = {DATA_WIDTH{1'b0}};

        // Keep master clock cycling to allow trailing pipeline elements to flush out
        #(CLK_PERIOD * 100);

        // Cleanly close out file operations
        $fclose(out_file);
        $display("[TB FINISH] Output log saved successfully to clean_dout.txt.");
        $finish;
    end

    // =========================================================================
    // Output Monitoring & Auto-Logging Task
    // =========================================================================
    always @(posedge clk) begin
        if (rst_n && clean_dout_valid) begin
            // Log output samples as signed integers to make plotting them in MATLAB trivial
            $fwrite(out_file, "%d\n", clean_dout);
            $display("Time: %0t ns | Corrected Output Data Step = %d", $time, clean_dout);
        end
    end

endmodule